name: release-please

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release-please:
    uses: mauhlik/reusable-workflows/.github/workflows/release-please.yml@v1
    with:
      environment: default
    secrets: inherit
